/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
export {}
declare global {
  const request: typeof import('zf-dbs')['request']
  const ue: typeof import('zf-dbs')['ue']
  const useBusinessPaging: typeof import('zf-vue-use')['useBusinessPaging']
  const useConfig: typeof import('zf-dbs')['useConfig']
  const useInterval: typeof import('zf-vue-use')['useInterval']
  const usePolling: typeof import('zf-dbs')['usePolling']
  const usePollingRef: typeof import('zf-dbs')['usePollingRef']
  const useTimeout: typeof import('zf-vue-use')['useTimeout']
}
