/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppLayout: typeof import('./../components/AppLayout/AppLayout.vue')['default']
    FloodPageLeftCard1: typeof import('./../components/FloodPageLeftCard1.vue')['default']
    FloodPageLeftCard2: typeof import('./../components/FloodPageLeftCard2.vue')['default']
    FloodPageLeftCard3: typeof import('./../components/FloodPageLeftCard3.vue')['default']
    FloodPageRightCard1: typeof import('./../components/FloodPageRightCard1.vue')['default']
    FloodPageRightCard2: typeof import('./../components/FloodPageRightCard2.vue')['default']
    FloodPageRightCard3: typeof import('./../components/FloodPageRightCard3.vue')['default']
    PageCard: typeof import('./../components/PageCard/index.vue')['default']
    PageDetails: typeof import('./../components/PageDetails/index.vue')['default']
    PageScreen: typeof import('./../components/PageScreen/PageScreen.vue')['default']
    PageTable: typeof import('./../components/PageTable/index.vue')['default']
    Pagination: typeof import('./../components/Pagination/Pagination.vue')['default']
    PreviewPageLeftCard1: typeof import('./../components/PreviewPageLeftCard1.vue')['default']
    PreviewPageLeftCard2: typeof import('./../components/PreviewPageLeftCard2.vue')['default']
    PreviewPageRightCard1: typeof import('./../components/PreviewPageRightCard1.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SituationPageLeftCard1: typeof import('./../components/SituationPageLeftCard1.vue')['default']
    SituationPageLeftCard2: typeof import('./../components/SituationPageLeftCard2.vue')['default']
    SituationPageLeftCard3: typeof import('./../components/SituationPageLeftCard3.vue')['default']
    SituationPageRightCard1: typeof import('./../components/SituationPageRightCard1.vue')['default']
    SituationPageRightCard2: typeof import('./../components/SituationPageRightCard2.vue')['default']
    SituationPageRightCard3: typeof import('./../components/SituationPageRightCard3.vue')['default']
    VideoPlay: typeof import('./../components/VideoPlay/VideoPlay.vue')['default']
    VideoPlayHls: typeof import('./../components/VideoPlay/VideoPlayHls.vue')['default']
    VueEcharts: typeof import('./../components/VueEcharts/VueEcharts.vue')['default']
    WaterPageLeftCard1: typeof import('./../components/WaterPageLeftCard1.vue')['default']
    WaterPageLeftCard2: typeof import('./../components/WaterPageLeftCard2.vue')['default']
    WaterPageLeftCard3: typeof import('./../components/WaterPageLeftCard3.vue')['default']
    WaterPageRightCard1: typeof import('./../components/WaterPageRightCard1.vue')['default']
    WaterPageRightCard2: typeof import('./../components/WaterPageRightCard2.vue')['default']
    ZfApp: typeof import('zf-dbs')['ZfApp']
    ZfTweenNumber: typeof import('zf-dbs')['ZfTweenNumber']
  }
}
